#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasta_Takip_Giriş
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DisciHasta")]
	public partial class DisciHastaLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoktor(Doktor instance);
    partial void UpdateDoktor(Doktor instance);
    partial void DeleteDoktor(Doktor instance);
    partial void InsertUygulama(Uygulama instance);
    partial void UpdateUygulama(Uygulama instance);
    partial void DeleteUygulama(Uygulama instance);
    partial void InsertHasta(Hasta instance);
    partial void UpdateHasta(Hasta instance);
    partial void DeleteHasta(Hasta instance);
    #endregion
		
		public DisciHastaLinqDataContext() : 
				base(global::Hasta_Takip_Giriş.Properties.Settings.Default.DisciHastaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DisciHastaLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DisciHastaLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DisciHastaLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DisciHastaLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Doktor> Doktors
		{
			get
			{
				return this.GetTable<Doktor>();
			}
		}
		
		public System.Data.Linq.Table<Uygulama> Uygulamas
		{
			get
			{
				return this.GetTable<Uygulama>();
			}
		}
		
		public System.Data.Linq.Table<Hasta> Hastas
		{
			get
			{
				return this.GetTable<Hasta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doktor")]
	public partial class Doktor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDoktor;
		
		private string _Doktor_isim;
		
		private string _Doktor_soyİsim;
		
		private System.Nullable<System.DateTime> _Doktor_dogumTarihi;
		
		private System.Nullable<System.DateTime> _Doktor_baslagıcTarihi;
		
		private System.Nullable<decimal> _Doktor_maas;
		
		private EntitySet<Uygulama> _Uygulamas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDoktorChanging(int value);
    partial void OnidDoktorChanged();
    partial void OnDoktor_isimChanging(string value);
    partial void OnDoktor_isimChanged();
    partial void OnDoktor_soyİsimChanging(string value);
    partial void OnDoktor_soyİsimChanged();
    partial void OnDoktor_dogumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDoktor_dogumTarihiChanged();
    partial void OnDoktor_baslagıcTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDoktor_baslagıcTarihiChanged();
    partial void OnDoktor_maasChanging(System.Nullable<decimal> value);
    partial void OnDoktor_maasChanged();
    #endregion
		
		public Doktor()
		{
			this._Uygulamas = new EntitySet<Uygulama>(new Action<Uygulama>(this.attach_Uygulamas), new Action<Uygulama>(this.detach_Uygulamas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDoktor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idDoktor
		{
			get
			{
				return this._idDoktor;
			}
			set
			{
				if ((this._idDoktor != value))
				{
					this.OnidDoktorChanging(value);
					this.SendPropertyChanging();
					this._idDoktor = value;
					this.SendPropertyChanged("idDoktor");
					this.OnidDoktorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doktor_isim", DbType="NVarChar(50)")]
		public string Doktor_isim
		{
			get
			{
				return this._Doktor_isim;
			}
			set
			{
				if ((this._Doktor_isim != value))
				{
					this.OnDoktor_isimChanging(value);
					this.SendPropertyChanging();
					this._Doktor_isim = value;
					this.SendPropertyChanged("Doktor_isim");
					this.OnDoktor_isimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doktor_soyİsim", DbType="NVarChar(50)")]
		public string Doktor_soyİsim
		{
			get
			{
				return this._Doktor_soyİsim;
			}
			set
			{
				if ((this._Doktor_soyİsim != value))
				{
					this.OnDoktor_soyİsimChanging(value);
					this.SendPropertyChanging();
					this._Doktor_soyİsim = value;
					this.SendPropertyChanged("Doktor_soyİsim");
					this.OnDoktor_soyİsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doktor_dogumTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Doktor_dogumTarihi
		{
			get
			{
				return this._Doktor_dogumTarihi;
			}
			set
			{
				if ((this._Doktor_dogumTarihi != value))
				{
					this.OnDoktor_dogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._Doktor_dogumTarihi = value;
					this.SendPropertyChanged("Doktor_dogumTarihi");
					this.OnDoktor_dogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doktor_baslagıcTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Doktor_baslagıcTarihi
		{
			get
			{
				return this._Doktor_baslagıcTarihi;
			}
			set
			{
				if ((this._Doktor_baslagıcTarihi != value))
				{
					this.OnDoktor_baslagıcTarihiChanging(value);
					this.SendPropertyChanging();
					this._Doktor_baslagıcTarihi = value;
					this.SendPropertyChanged("Doktor_baslagıcTarihi");
					this.OnDoktor_baslagıcTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doktor_maas", DbType="Money")]
		public System.Nullable<decimal> Doktor_maas
		{
			get
			{
				return this._Doktor_maas;
			}
			set
			{
				if ((this._Doktor_maas != value))
				{
					this.OnDoktor_maasChanging(value);
					this.SendPropertyChanging();
					this._Doktor_maas = value;
					this.SendPropertyChanged("Doktor_maas");
					this.OnDoktor_maasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doktor_Uygulama", Storage="_Uygulamas", ThisKey="idDoktor", OtherKey="Uygulama_idDoktor")]
		public EntitySet<Uygulama> Uygulamas
		{
			get
			{
				return this._Uygulamas;
			}
			set
			{
				this._Uygulamas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uygulamas(Uygulama entity)
		{
			this.SendPropertyChanging();
			entity.Doktor = this;
		}
		
		private void detach_Uygulamas(Uygulama entity)
		{
			this.SendPropertyChanging();
			entity.Doktor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uygulama")]
	public partial class Uygulama : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _Uygulama_idDoktor;
		
		private System.Nullable<int> _Uygulama_idHasta;
		
		private System.Nullable<System.DateTime> _Uygulama_tarihSaat;
		
		private string _Uygulama_açıklama;
		
		private System.Nullable<decimal> _Uygulama_fiyat;
		
		private EntityRef<Doktor> _Doktor;
		
		private EntityRef<Hasta> _Hasta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUygulama_idDoktorChanging(System.Nullable<int> value);
    partial void OnUygulama_idDoktorChanged();
    partial void OnUygulama_idHastaChanging(System.Nullable<int> value);
    partial void OnUygulama_idHastaChanged();
    partial void OnUygulama_tarihSaatChanging(System.Nullable<System.DateTime> value);
    partial void OnUygulama_tarihSaatChanged();
    partial void OnUygulama_açıklamaChanging(string value);
    partial void OnUygulama_açıklamaChanged();
    partial void OnUygulama_fiyatChanging(System.Nullable<decimal> value);
    partial void OnUygulama_fiyatChanged();
    #endregion
		
		public Uygulama()
		{
			this._Doktor = default(EntityRef<Doktor>);
			this._Hasta = default(EntityRef<Hasta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uygulama_idDoktor", DbType="Int")]
		public System.Nullable<int> Uygulama_idDoktor
		{
			get
			{
				return this._Uygulama_idDoktor;
			}
			set
			{
				if ((this._Uygulama_idDoktor != value))
				{
					if (this._Doktor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUygulama_idDoktorChanging(value);
					this.SendPropertyChanging();
					this._Uygulama_idDoktor = value;
					this.SendPropertyChanged("Uygulama_idDoktor");
					this.OnUygulama_idDoktorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uygulama_idHasta", DbType="Int")]
		public System.Nullable<int> Uygulama_idHasta
		{
			get
			{
				return this._Uygulama_idHasta;
			}
			set
			{
				if ((this._Uygulama_idHasta != value))
				{
					if (this._Hasta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUygulama_idHastaChanging(value);
					this.SendPropertyChanging();
					this._Uygulama_idHasta = value;
					this.SendPropertyChanged("Uygulama_idHasta");
					this.OnUygulama_idHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uygulama_tarihSaat", DbType="DateTime", IsPrimaryKey=true)]
		public System.Nullable<System.DateTime> Uygulama_tarihSaat
		{
			get
			{
				return this._Uygulama_tarihSaat;
			}
			set
			{
				if ((this._Uygulama_tarihSaat != value))
				{
					this.OnUygulama_tarihSaatChanging(value);
					this.SendPropertyChanging();
					this._Uygulama_tarihSaat = value;
					this.SendPropertyChanged("Uygulama_tarihSaat");
					this.OnUygulama_tarihSaatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uygulama_açıklama", DbType="NVarChar(MAX)")]
		public string Uygulama_açıklama
		{
			get
			{
				return this._Uygulama_açıklama;
			}
			set
			{
				if ((this._Uygulama_açıklama != value))
				{
					this.OnUygulama_açıklamaChanging(value);
					this.SendPropertyChanging();
					this._Uygulama_açıklama = value;
					this.SendPropertyChanged("Uygulama_açıklama");
					this.OnUygulama_açıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uygulama_fiyat", DbType="Money")]
		public System.Nullable<decimal> Uygulama_fiyat
		{
			get
			{
				return this._Uygulama_fiyat;
			}
			set
			{
				if ((this._Uygulama_fiyat != value))
				{
					this.OnUygulama_fiyatChanging(value);
					this.SendPropertyChanging();
					this._Uygulama_fiyat = value;
					this.SendPropertyChanged("Uygulama_fiyat");
					this.OnUygulama_fiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doktor_Uygulama", Storage="_Doktor", ThisKey="Uygulama_idDoktor", OtherKey="idDoktor", IsForeignKey=true)]
		public Doktor Doktor
		{
			get
			{
				return this._Doktor.Entity;
			}
			set
			{
				Doktor previousValue = this._Doktor.Entity;
				if (((previousValue != value) 
							|| (this._Doktor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Doktor.Entity = null;
						previousValue.Uygulamas.Remove(this);
					}
					this._Doktor.Entity = value;
					if ((value != null))
					{
						value.Uygulamas.Add(this);
						this._Uygulama_idDoktor = value.idDoktor;
					}
					else
					{
						this._Uygulama_idDoktor = default(Nullable<int>);
					}
					this.SendPropertyChanged("Doktor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hasta_Uygulama", Storage="_Hasta", ThisKey="Uygulama_idHasta", OtherKey="idHasta", IsForeignKey=true)]
		public Hasta Hasta
		{
			get
			{
				return this._Hasta.Entity;
			}
			set
			{
				Hasta previousValue = this._Hasta.Entity;
				if (((previousValue != value) 
							|| (this._Hasta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hasta.Entity = null;
						previousValue.Uygulamas.Remove(this);
					}
					this._Hasta.Entity = value;
					if ((value != null))
					{
						value.Uygulamas.Add(this);
						this._Uygulama_idHasta = value.idHasta;
					}
					else
					{
						this._Uygulama_idHasta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hasta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hasta")]
	public partial class Hasta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idHasta;
		
		private string _Hasta_isim;
		
		private string _Hasta_soyİsim;
		
		private System.Nullable<System.DateTime> _Hasta_dogumTarihi;
		
		private System.Nullable<System.DateTime> _Hasta_basvuruTarihi;
		
		private string _Hasta_telefon;
		
		private EntitySet<Uygulama> _Uygulamas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHastaChanging(int value);
    partial void OnidHastaChanged();
    partial void OnHasta_isimChanging(string value);
    partial void OnHasta_isimChanged();
    partial void OnHasta_soyİsimChanging(string value);
    partial void OnHasta_soyİsimChanged();
    partial void OnHasta_dogumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnHasta_dogumTarihiChanged();
    partial void OnHasta_basvuruTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnHasta_basvuruTarihiChanged();
    partial void OnHasta_telefonChanging(string value);
    partial void OnHasta_telefonChanged();
    #endregion
		
		public Hasta()
		{
			this._Uygulamas = new EntitySet<Uygulama>(new Action<Uygulama>(this.attach_Uygulamas), new Action<Uygulama>(this.detach_Uygulamas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHasta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idHasta
		{
			get
			{
				return this._idHasta;
			}
			set
			{
				if ((this._idHasta != value))
				{
					this.OnidHastaChanging(value);
					this.SendPropertyChanging();
					this._idHasta = value;
					this.SendPropertyChanged("idHasta");
					this.OnidHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hasta_isim", DbType="NVarChar(50)")]
		public string Hasta_isim
		{
			get
			{
				return this._Hasta_isim;
			}
			set
			{
				if ((this._Hasta_isim != value))
				{
					this.OnHasta_isimChanging(value);
					this.SendPropertyChanging();
					this._Hasta_isim = value;
					this.SendPropertyChanged("Hasta_isim");
					this.OnHasta_isimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hasta_soyİsim", DbType="NVarChar(50)")]
		public string Hasta_soyİsim
		{
			get
			{
				return this._Hasta_soyİsim;
			}
			set
			{
				if ((this._Hasta_soyİsim != value))
				{
					this.OnHasta_soyİsimChanging(value);
					this.SendPropertyChanging();
					this._Hasta_soyİsim = value;
					this.SendPropertyChanged("Hasta_soyİsim");
					this.OnHasta_soyİsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hasta_dogumTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Hasta_dogumTarihi
		{
			get
			{
				return this._Hasta_dogumTarihi;
			}
			set
			{
				if ((this._Hasta_dogumTarihi != value))
				{
					this.OnHasta_dogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._Hasta_dogumTarihi = value;
					this.SendPropertyChanged("Hasta_dogumTarihi");
					this.OnHasta_dogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hasta_basvuruTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Hasta_basvuruTarihi
		{
			get
			{
				return this._Hasta_basvuruTarihi;
			}
			set
			{
				if ((this._Hasta_basvuruTarihi != value))
				{
					this.OnHasta_basvuruTarihiChanging(value);
					this.SendPropertyChanging();
					this._Hasta_basvuruTarihi = value;
					this.SendPropertyChanged("Hasta_basvuruTarihi");
					this.OnHasta_basvuruTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hasta_telefon", DbType="NChar(10)")]
		public string Hasta_telefon
		{
			get
			{
				return this._Hasta_telefon;
			}
			set
			{
				if ((this._Hasta_telefon != value))
				{
					this.OnHasta_telefonChanging(value);
					this.SendPropertyChanging();
					this._Hasta_telefon = value;
					this.SendPropertyChanged("Hasta_telefon");
					this.OnHasta_telefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hasta_Uygulama", Storage="_Uygulamas", ThisKey="idHasta", OtherKey="Uygulama_idHasta")]
		public EntitySet<Uygulama> Uygulamas
		{
			get
			{
				return this._Uygulamas;
			}
			set
			{
				this._Uygulamas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uygulamas(Uygulama entity)
		{
			this.SendPropertyChanging();
			entity.Hasta = this;
		}
		
		private void detach_Uygulamas(Uygulama entity)
		{
			this.SendPropertyChanging();
			entity.Hasta = null;
		}
	}
}
#pragma warning restore 1591
